version: '3.8'
services:
  app:
    image: tu-imagen
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection="Server=tcp:loteria-gruposim.database.windows.net,1433; Initial Catalog=Loteria; Persist Security Info=False; User ID= Gruposim; Password=Perrilla2024@;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "tu-contraseña"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"